web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
db:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - /opt/mysql_data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=Crown54321
    - MYSQL_USER=guan
    - MYSQL_PASSWORD=Crown54321
    - MYSQL_DATABASE=guandb
